### PR TITLE
Add new blog post: Outreachy Contributor Guide

### PR DESCRIPTION
**Pull request by MSanKeys963**
Added new blog post: 'Outreachy Contributor Guide.'
Link for the blog post: https://zarr.dev/blog/outreachy-contributor-guide/

### CODE REVIEW

**Comment by MSanKeys963** [comment]
CC: @joshmoore

**Comment by joshmoore** [comment]
:+1:

**Comment by jakirkham** [comment]
Thanks Sanket! 🙏

Also +1 on the separate Gitter channel. We did the same in conda-forge and it was very helpful.

**Comment by MSanKeys963** [comment]
Yes! We didn't expect so many contributors in the initial phase.

**Pull request merged**
