### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by MSanKeys963**
Hi all. 👋🏻

This PR adds a LICENSE file to the repository. Please review.

Thanks!

### CODE REVIEW

**Comment by joshmoore** [comment]
I'm not sure if CC0 can be blanket applied to this repo especially if we're accepting content from others. Would anyone have an objection to CC-BY?

**Comment by MSanKeys963** [comment]
Is there a license appropriate for this repository?

**Comment by jhamman** [comment]
CC-BY on blog content makes sense to me.

**Comment by jakirkham** [comment]
Yeah CC-BY seems fine. We already use this in other places (like the specs)

**Comment by MSanKeys963** [comment]
Closing this in favour of #56.

**Pull request closed without merging**
